version: 2.1

jobs:
  app-build:
    docker:
      - image: alpine
    steps:
      - common-say-hello:
          to: C
      - run: echo 'Hello world from app package!'

workflows:
  app-workflow:
    jobs:
      - app-build