version: 2.1

jobs:
  auth-build:
    docker:
      - image: alpine
    steps:
      - common-say-hello:
          to: C
      - run: echo 'Hello world from auth package!'

workflows:
  auth-workflow:
    jobs: 
      - auth-build